import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@/styles/global.css';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';

import ReactQueryProvider from '@/providers/TanstackProvider';
import ThemeRegistry from '@/styles/theme/ThemeRegistry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Gestão | ASSIM',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <head>
        {metadata.title && <title>{String(metadata.title)}</title>}
        {metadata.description && (
          <meta name="description" content={metadata.description} />
        )}
      </head>
      <body className={inter.className}>
        <ReactQueryProvider>
          <ThemeRegistry>
            <Navbar />
            {children}
            <Footer />
          </ThemeRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
